_target_: alpamayo.processor.qwen_processor.get_preprocess_data_fn_from_model_config
# Supported components:
#   User:      image, traj_history, route, question, prompt
#   Assistant:  cot, meta_action, traj_future, answer
components_order: ["image", "traj_history", "prompt", "traj_future"]
components_prompt: ["traj_future"]
label_components: ["traj_future"]
include_camera_ids: false